<a href="https://colab.research.google.com/github/MisirHuseynov/number-one/blob/main/kontakt_parsing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests as req
from bs4 import BeautifulSoup as bs
import pandas as pd
class parsing:
  def __init__(self):
    self.a={}
  def kontakt(self):
    i=0
    baza={}
    for x in range(3):
      url=str(input('linki daxil edin:'))
      page=req.get(url)
      soup=bs(page.content,'html.parser')
      marka=soup.find(attrs={'class':'title'}).text.strip()
      qiymet=soup.find(attrs={'class':'gridprice gridprice_cash'}).text.strip()
      baza.update({marka:[qiymet]})
      i+=1
      i
      self.a.update({'kontakt home':baza})
    ab=pd.DataFrame(self.a)
    ab.to_csv('file.csv')
    df=pd.read_csv('file.csv')
    display(baza)
    print('********')
    display(self.a)
    display(df)
netice=parsing()
netice.kontakt()

linki daxil edin:https://kontakt.az/samsung-galaxy-s22-sm-s901b-phantom-black/
linki daxil edin:https://kontakt.az/samsung-galaxy-a13-ds-sm-a135-64-gb-black/
linki daxil edin:https://kontakt.az/samsung-galaxy-a03-64gb-sm-a035-black/

{'Samsung Galaxy S22 (SM-S901B) Phantom Black': ['1799.99 M'],
 'Samsung Galaxy A13 DS (SM-A135) 64 GB Black': ['429.99 M'],
 'Samsung Galaxy A03 64 GB (SM-A035) Black': ['289.99 M']}

********

{'kontakt home': {'Samsung Galaxy S22 (SM-S901B) Phantom Black': ['1799.99 M'],
  'Samsung Galaxy A13 DS (SM-A135) 64 GB Black': ['429.99 M'],
  'Samsung Galaxy A03 64 GB (SM-A035) Black': ['289.99 M']}}

                                    Unnamed: 0   kontakt home
0     Samsung Galaxy A03 64 GB (SM-A035) Black   ['289.99 M']
1  Samsung Galaxy A13 DS (SM-A135) 64 GB Black   ['429.99 M']
2  Samsung Galaxy S22 (SM-S901B) Phantom Black  ['1799.99 M']

In [ ]:

df=pd.read_csv('file (3).csv')
df

                                    mehsul adi   kontakt home
0     Samsung Galaxy A03 64 GB (SM-A035) Black   ['289.99 M']
1  Samsung Galaxy A13 DS (SM-A135) 64 GB Black   ['429.99 M']
2  Samsung Galaxy S22 (SM-S901B) Phantom Black  ['1799.99 M']